export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
export const GET_SUCCESS_LOGIN = 'GET_SUCCESS_LOGIN';
export const GET_FAIL_LOGIN = 'GET_FAIL_LOGIN';